New features addition
skanelo/mlops-workflow pull request #2
Opened 2023-11-22 19:19 UTC by skanelo

New features
- two functions (addition and subtraction)
- tests for these two functions
- add GHA to run checks each time a commit/PR takes place

Updates
- poetry.lock and pyproject.toml
- .gitignore file

2023-11-24 18:11 UTC, pvardanis requested changes
@skanelo αν εχεις κανει commit και μετα αλλαζεις κατι στο ιδιο commit, απεφευγε να κανεις commit με το ιδιο message. Μπορεις απλα να κανεις `git commit --amend` και να κανεις edit το commit message που θα σου ανοιξει, η απλα `git commit --amend --no-edit` για να χρησιμοποιησεις το ιδιο ακριβως commit message.

2023-11-24 18:13 UTC, pvardanis commented on .github/workflows/pre-commit.yml
> +        run: poetry install --no-interaction
@skanelo αυτο εδω θα μπορουσε να ειναι `make` command, να μπορεις να το χρησιμοποιεις και locally

2023-11-24 18:15 UTC, pvardanis commented on .github/workflows/pre-commit.yml
> +      - name: Install Poetry
@skanelo μπορεις να cachαρεις και το `poetry`, οπως εκανες με το `venv`. Κατι τύπου:

2023-11-24 18:16 UTC, pvardanis commented on .github/workflows/pre-commit.yml
> +      - name: Install Project
@skanelo "install dependencies" καλυτερα?

2023-11-24 18:19 UTC, pvardanis commented on .github/workflows/pre-commit.yml
> +          source .venv/bin/activate
@skanelo δεν ειναι `pre-commit` checks αυτα, το commit εχει ηδη γινει :P Αν θες ομως μπορεις να σεταρεις ενα [pre-commit](https://pre-commit.com/) config, που θα τρεχει αυτοματα καθε φορα που θα κανεις commit locally.

Επισης αυτες οι εντολες εδω καλυτερα να ειναι ολες make commands. Και επισης προτεινω καθε ενα απο τα checks που κανεις να ειναι διαφορετικο `job`, η τουλαχιστον `step` για να τρεχουν ενα ενα και να βλεπεις το progress, βοηθαει και με το debug.

2023-11-24 18:24 UTC, pvardanis commented on tests/test_main.py
> +def test_add_two_numbers_positive() -> None:
@skanelo μπορεις να παραμετροποιησεις το test σου αφου τεσταρεις το ιδιο function με το [@pytest.mark.parametrize](https://docs.pytest.org/en/7.1.x/how-to/parametrize.html) decorator.

Πχ:

```python

@pytest.mark.parametrize(
    "a, b, expected_result",
    [
        (3, 5, 8),
        (-2, 7, 5),
    ],
)
def test_add_two_numbers(a, b, expected_result) -> None:
    result = add_two_numbers(a, b)
    assert result == expected_result
```

2023-11-24 18:28 UTC, pvardanis commented on .github/workflows/pre-commit.yml
> +name: Pre-Commit Checks
@skanelo δεν ειναι `pre-commit` αυτο το `workflow` αφου το εχεις ηδη pushaρει στο github

2023-11-24 18:32 UTC, pvardanis commented on pyproject.toml
>  pytest = "^7.4.2"
@skanelo μπορεις να ρυθμισεις το `threshold` ετσι ωστε να failαρει αν εχεις coverage κατω απο αυτο.

```
[tool.pytest.ini_options]
addopts = "--cov-fail-under=80"
```

2023-11-26 14:23 UTC, skanelo commented on .github/workflows/pre-commit.yml
> +        run: poetry install --no-interaction
Ωστε να εχω και καλα ολες τις εντολες του bash σε ενα makefile και τελικα στο .yml να τρεχω μονο ενα make?
Γιαυτο το προτεινεις αυτο?

2023-11-26 14:28 UTC, skanelo commented on pyproject.toml
>  pytest = "^7.4.2"
Sweeet!

2023-11-26 17:45 UTC, skanelo commented on .github/workflows/pre-commit.yml
> +      - name: Install Poetry
Δε βλεπω τι αλλο μπορω να κανω. Με βαση αυτο το [post](https://stackoverflow.com/questions/62977821/how-to-cache-poetry-install-for-github-actions) εχουμε κανει το ιδιο πραγμα.

Αυτο που καταλαβαινω ειναι οτι:
1. Κανω install το poetry
2. Κανω load to cached venv (αν ειναι η πρωτη φορα δε θα υπαρχει, αλλιως θα το loadαρει)
3. Αν το venv εχει loadαριστει δε θα τρεξει το poetry install --no-interaction, αλλιως θα το τρεξει.

2023-11-26 18:06 UTC, skanelo commented on .github/workflows/pre-commit.yml
> +          source .venv/bin/activate
Aν ειναι μεσα σε Makefile πως θα γινει αυτο?

2023-11-26 23:16 UTC, skanelo commented on tests/test_main.py
> +def test_add_two_numbers_positive() -> None:
Πιο μετα που τα tests θα γινουν πιο περιπλοκα δε θα βοηθαει να εχω type annotations?
Δε θελω τα tests να ειναι εξισου readable κ easily maintainable?

2023-12-08 10:12 UTC, pvardanis approved these changes

2023-12-08 10:15 UTC, merged